name: secret-token
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  secret:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use secret
        env:
          SUPER_SECRET: ${{ secrets.SUPER_SECRET }}
        run:
          if [[ -z "$SUPER_SECRET" ]]; then
            echo "No super available"
            exit 1
          fi
