name: publish
on:
  pull_request_target:
    types: [labeled]
jobs:
  canary:
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'joshblack/actions-security' && contains(github.event.pull_request.labels.*.name, 'Deploy Canary') }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - name: npm publish
        run: |
          $HASH=$(git rev-parse --short "$GITHUB_SHA")
          cd packages/add
          echo "$(jq '.version = "0.0.0-$HASH"' package.json )" > package.json
          cat package.json
          # npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
