name: secret
on:
  workflow_run:
    workflows: ["ci"]
    types:
      - completed
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  secret:
    if: >
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    permissions:
      statuses: write 
    steps:
      - uses: actions/checkout@v3
      - name: Use secret
        env:
          SUPER_SECRET: ${{ secrets.SUPER_SECRET }}
        run: |
          if [[ -z "$SUPER_SECRET" ]]; then
            echo "No secret available"
            exit 1
          fi
      - uses: actions/github-script@v6
        with:
          script: |
            console.log(JSON.stringify(context, null, 2))
            // octokit.rest.checks.createSuite({
              // owner: context.repo.owner,
              // repo: context.repo.repo,
              // head_sha,
            // });
