name: vrt
on:
  workflow_run:
    workflows: [ci]
    types:
      - completed

jobs:
  chromatic:
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/github-script@v3.1.0
        with:
          script: |
            const fs = require('fs');
            const artifacts = await github.actions.listWorkflowRunArtifacts({
                owner: context.repo.owner,
                repo: context.repo.repo,
                run_id: ${{ github.event.workflow_run.id }},
            });
            const [matchArtifact] = artifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "storybook"
            });
            const download = await github.actions.downloadArtifact({
                owner: context.repo.owner,
                repo: context.repo.repo,
                artifact_id: matchArtifact.id,
                archive_format: 'zip',
            });
            fs.writeFileSync('${{github.workspace}}/storybook.zip', Buffer.from(download.data));
      - run: unzip storybook.zip -d storybook-static
      - name: Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_KEY }}
          autoAcceptChanges: github.ref == 'refs/heads/main'
          onlyChanged: true
          storybookBuildDir: storybook-static
