name: workflow-run
on:
  workflow_run:
    workflows: [ci]
    types:
      - completed

jobs:
  event:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.event == 'pull_request'
    steps:
      - uses: actions/github-script@v3.1.0
        with:
          script: |
            const { payload } = context;
            const run = payload.workflow_run;
            const pull_requests = run.pull_requests;
            if (pull_requests.length > 1) {
              core.warn('More than one pull request associated with this workflow_run');
            }
            
            console.log(payload.workflow_run);
            
            console.log(pull_requests);

            const [pull_request] = pull_requests;
            const labels = await github.issues.listLabelsOnIssue({
              owner: payload.repository.owner.login,
              repo: payload.repository.name,
              issue_number: pull_request.number,
            });

            console.log(labels);
